### ISSUE TITLE
20秋季学期课表无法更新

### ISSUE THREAD

**Issue by ShiZhuming** [li3zhen1/PkuScheduler#2]
首先感谢你写了这个工具，很好用！

20秋季学期，学校课表上游数据源可能发生了更新，参考pkuhelper最新的更新，pkuscheduler的课表还是上学期的无法更新，你有精力修复这个接口问题吗？我也可以改一下然后提pr，我们可以用shizhuming@pku.edu.cn联系。

**Comment by HereIsLz** [comment]
你好，因为上学期赶工没有写更新功能，如果需要查看新学期的课程表，可以通过清除 Pku Scheduler 的存储和缓存或者重新安装来使用。我们正在重构 Pku Scheduler 以提供更完整的应用体验（https://github.com/HereIsLz/Scheduler，暂时不可用）。
